// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: uploadClient.proto

package uploadClient

import (
	"context"

	"server/rpc/upload/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadReq  = pb.UploadReq
	UploadResp = pb.UploadResp

	Upload interface {
		UploadFile(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error)
	}

	defaultUpload struct {
		cli zrpc.Client
	}
)

func NewUpload(cli zrpc.Client) Upload {
	return &defaultUpload{
		cli: cli,
	}
}

func (m *defaultUpload) UploadFile(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error) {
	client := pb.NewUploadClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}
