// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetCurrentUserResp struct {
	Id       int64   `json:"id"`
	Username string  `json:"username"`
	Role     int32   `json:"role"`
	RoleName string  `json:"roleName"`       // 角色名称
	Phone    *string `json:"phone,optional"` // 手机号
	Email    *string `json:"email,optional"` // 邮箱
}

type LoginReq struct {
	Username string `json:"username,optional"` // 用户名
	Password string `json:"password,optional"` // 密码
}

type LoginResp struct {
	AccessToken  string   `json:"accessToken"`  // 访问令牌 (JWT)
	RefreshToken string   `json:"refreshToken"` // 刷新令牌 (JWT)
	ExpireIn     int64    `json:"expireIn"`     // Access过期时间(秒)
	UserInfo     UserInfo `json:"userInfo"`     // 用户信息
}

type LogoutResp struct {
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken,optional"` // 刷新令牌
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`  // 新的访问令牌
	RefreshToken string `json:"refreshToken"` // 新的刷新令牌
	ExpireIn     int64  `json:"expireIn"`     // Access过期时间(秒)
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Role     int32  `json:"role"`
	RoleName string `json:"roleName"` // 角色名称: 管理员/超级管理员
}
