// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: upload.proto

package server

import (
	"context"

	"server/rpc/upload/internal/logic"
	"server/rpc/upload/internal/svc"
	"server/rpc/upload/pb"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadServer) UploadFile(ctx context.Context, in *pb.UploadReq) (*pb.UploadResp, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
