// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	banner "server/gateway/internal/handler/banner"
	classschedule "server/gateway/internal/handler/class/schedule"
	coach "server/gateway/internal/handler/coach"
	coreadvantage "server/gateway/internal/handler/core/advantage"
	courseCourse "server/gateway/internal/handler/course/Course"
	coursecategory "server/gateway/internal/handler/course/category"
	courseclass "server/gateway/internal/handler/course/class"
	feedback "server/gateway/internal/handler/feedback"
	frontendabout "server/gateway/internal/handler/frontend/about"
	frontendcoaches "server/gateway/internal/handler/frontend/coaches"
	frontendcourses "server/gateway/internal/handler/frontend/courses"
	frontendhome "server/gateway/internal/handler/frontend/home"
	institutionfacility "server/gateway/internal/handler/institution/facility"
	institutionhonor "server/gateway/internal/handler/institution/honor"
	institutioninfo "server/gateway/internal/handler/institution/info"
	institutionmilestone "server/gateway/internal/handler/institution/milestone"
	quickentry "server/gateway/internal/handler/quick/entry"
	registration "server/gateway/internal/handler/registration"
	studentStudent "server/gateway/internal/handler/student/Student"
	studentattendance "server/gateway/internal/handler/student/attendance"
	studentenrollment "server/gateway/internal/handler/student/enrollment"
	studentfitnessTest "server/gateway/internal/handler/student/fitnessTest"
	studentgrowthRecord "server/gateway/internal/handler/student/growthRecord"
	sysconfig "server/gateway/internal/handler/sys/config"
	sysoperationLog "server/gateway/internal/handler/sys/operationLog"
	sysuser "server/gateway/internal/handler/sys/user"
	upload "server/gateway/internal/handler/upload"
	"server/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: banner.CreateBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: banner.ListBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: banner.UpdateBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: banner.FindBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: banner.DeleteBannerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/banner"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: classschedule.CreateScheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: classschedule.ListScheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: classschedule.UpdateScheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: classschedule.FindScheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: classschedule.DeleteScheduleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/class/schedule"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: coach.CreateCoachHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: coach.ListCoachHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: coach.UpdateCoachHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: coach.FindCoachHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: coach.DeleteCoachHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/coach"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: coreadvantage.CreateAdvantageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: coreadvantage.ListAdvantageHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: coreadvantage.UpdateAdvantageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: coreadvantage.FindAdvantageHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: coreadvantage.DeleteAdvantageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/core/advantage"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: courseCourse.CreateCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: courseCourse.ListCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: courseCourse.UpdateCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: courseCourse.FindCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: courseCourse.DeleteCourseHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/course/Course"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: coursecategory.CreateCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: coursecategory.ListCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: coursecategory.UpdateCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: coursecategory.FindCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: coursecategory.DeleteCategoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/course/category"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: courseclass.CreateClassHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: courseclass.ListClassHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: courseclass.UpdateClassHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: courseclass.FindClassHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: courseclass.DeleteClassHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/course/class"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: feedback.CreateFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: feedback.ListFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: feedback.UpdateFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: feedback.FindFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: feedback.DeleteFeedbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/feedback"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/facility",
				Handler: frontendabout.GetFacilityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/honor",
				Handler: frontendabout.GetHonorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: frontendabout.GetInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/frontend/about"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ListCoaches",
				Handler: frontendcoaches.GetCoachesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/frontend/coaches"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/CourseCategory",
				Handler: frontendcourses.GetCourseCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/CourseList",
				Handler: frontendcourses.GetCourseListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/frontend/courses"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: frontendhome.GetBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/coreStrengths",
				Handler: frontendhome.GetCoreStrengthsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/frontend/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: institutionfacility.CreateFacilityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: institutionfacility.ListFacilityHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: institutionfacility.UpdateFacilityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: institutionfacility.FindFacilityHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: institutionfacility.DeleteFacilityHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/institution/facility"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: institutionhonor.CreateHonorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: institutionhonor.ListHonorHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: institutionhonor.UpdateHonorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: institutionhonor.FindHonorHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: institutionhonor.DeleteHonorHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/institution/honor"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: institutioninfo.CreateInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: institutioninfo.ListInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: institutioninfo.UpdateInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: institutioninfo.FindInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: institutioninfo.DeleteInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/institution/info"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: institutionmilestone.CreateMilestoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: institutionmilestone.ListMilestoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: institutionmilestone.UpdateMilestoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: institutionmilestone.FindMilestoneHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: institutionmilestone.DeleteMilestoneHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/institution/milestone"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: quickentry.CreateEntryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: quickentry.ListEntryHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: quickentry.UpdateEntryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: quickentry.FindEntryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: quickentry.DeleteEntryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/quick/entry"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: registration.CreateRegistrationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: registration.ListRegistrationHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: registration.UpdateRegistrationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: registration.FindRegistrationHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: registration.DeleteRegistrationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/registration"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: studentStudent.CreateStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: studentStudent.ListStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: studentStudent.UpdateStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: studentStudent.FindStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: studentStudent.DeleteStudentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/student/Student"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: studentattendance.CreateAttendanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: studentattendance.ListAttendanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: studentattendance.UpdateAttendanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: studentattendance.FindAttendanceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: studentattendance.DeleteAttendanceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/student/attendance"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: studentenrollment.CreateEnrollmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: studentenrollment.ListEnrollmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: studentenrollment.UpdateEnrollmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: studentenrollment.FindEnrollmentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: studentenrollment.DeleteEnrollmentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/student/enrollment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: studentfitnessTest.CreateFitnessTestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: studentfitnessTest.ListFitnessTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: studentfitnessTest.UpdateFitnessTestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: studentfitnessTest.FindFitnessTestHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: studentfitnessTest.DeleteFitnessTestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/student/fitnessTest"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: studentgrowthRecord.CreateGrowthRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: studentgrowthRecord.ListGrowthRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: studentgrowthRecord.UpdateGrowthRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: studentgrowthRecord.FindGrowthRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: studentgrowthRecord.DeleteGrowthRecordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/student/growthRecord"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sysconfig.CreateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sysconfig.ListConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: sysconfig.UpdateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sysconfig.FindConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: sysconfig.DeleteConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/sys/config"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sysoperationLog.CreateOperationLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sysoperationLog.ListOperationLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: sysoperationLog.UpdateOperationLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sysoperationLog.FindOperationLogHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: sysoperationLog.DeleteOperationLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/sys/operationLog"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sysuser.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sysuser.ListUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: sysuser.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sysuser.FindUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:ids",
				Handler: sysuser.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/sys/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uploadImages",
				Handler: upload.UploadImagesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/upload"),
	)
}
